package netgest.bo.xwc.components;

import netgest.bo.xwc.framework.jsf.XUIWriterAttributeConst;

public final class HTMLAttr {
    
    public static final Attr ABBR = new Attr( "abbr" );
    public static final Attr ACCEPT_CHARSET = new Attr( "accept-charset" );
    public static final Attr ACCEPT = new Attr( "accept" );
    public static final Attr ACCESSKEY = new Attr( "accesskey" );
    public static final Attr ACTION = new Attr( "action" );
    public static final Attr ALIGN = new Attr( "align" );
    public static final Attr ALINK = new Attr( "alink" );
    public static final Attr ALT = new Attr( "alt" );
    public static final Attr ARCHIVE = new Attr( "archive" );
    public static final Attr AXIS = new Attr( "axis" );
    public static final Attr BACKGROUND = new Attr( "background" );
    public static final Attr BGCOLOR = new Attr( "bgcolor" );
    public static final Attr BORDER = new Attr( "border" );
    public static final Attr CELLPADDING = new Attr( "cellpadding" );
    public static final Attr CELLSPACING = new Attr( "cellspacing" );
    public static final Attr CHAR = new Attr( "char" );
    public static final Attr CHAROFF = new Attr( "charoff" );
    public static final Attr CHARSET = new Attr( "charset" );
    public static final Attr CHECKED = new Attr( "checked" );
    public static final Attr CITE = new Attr( "cite" );
    public static final Attr CLASS = new Attr( "class" );
    public static final Attr CLASSID = new Attr( "classid" );
    public static final Attr CLEAR = new Attr( "clear" );
    public static final Attr CODE = new Attr( "code" );
    public static final Attr CODEBASE = new Attr( "codebase" );
    public static final Attr CODETYPE = new Attr( "codetype" );
    public static final Attr COLOR = new Attr( "color" );
    public static final Attr COLS = new Attr( "cols" );
    public static final Attr COLSPAN = new Attr( "colspan" );
    public static final Attr COMPACT = new Attr( "compact" );
    public static final Attr CONTENT = new Attr( "content" );
    public static final Attr COORDS = new Attr( "coords" );
    public static final Attr DATA = new Attr( "data" );
    public static final Attr DATETIME = new Attr( "datetime" );
    public static final Attr DECLARE = new Attr( "declare" );
    public static final Attr DEFER = new Attr( "defer" );
    public static final Attr DIR = new Attr( "dir" );
    public static final Attr DISABLED = new Attr( "disabled" );
    public static final Attr ENCTYPE = new Attr( "enctype" );
    public static final Attr FACE = new Attr( "face" );
    public static final Attr FOR = new Attr( "for" );
    public static final Attr FRAME = new Attr( "frame" );
    public static final Attr FRAMEBORDER = new Attr( "frameborder" );
    public static final Attr HEADERS = new Attr( "headers" );
    public static final Attr HEIGHT = new Attr( "height" );
    public static final Attr HREF = new Attr( "href" );
    public static final Attr HREFANG = new Attr( "hrefang" );
    public static final Attr HSPACE = new Attr( "hspace" );
    public static final Attr HTTP_EQUIV = new Attr( "http-equiv" );
    public static final Attr ID = new Attr( "id" );
    public static final Attr ISMAP = new Attr( "ismap" );
    public static final Attr LABEL = new Attr( "label" );
    public static final Attr LANG = new Attr( "lang" );
    public static final Attr LANGUAGE = new Attr( "language" );
    public static final Attr LINK = new Attr( "link" );
    public static final Attr LONGDESC = new Attr( "longdesc" );
    public static final Attr MARGINHEIGHT = new Attr( "marginheight" );
    public static final Attr MARGINWIDTH = new Attr( "marginwidth" );
    public static final Attr MAXLENGTH = new Attr( "maxlength" );
    public static final Attr MEDIA = new Attr( "media" );
    public static final Attr METHOD = new Attr( "method" );
    public static final Attr MULTIPLE = new Attr( "multiple" );
    public static final Attr NAME = new Attr( "name" );
    public static final Attr NOHREF = new Attr( "nohref" );
    public static final Attr NORESIZE = new Attr( "noresize" );
    public static final Attr NOSHADE = new Attr( "noshade" );
    public static final Attr NOWRAP = new Attr( "nowrap" );
    public static final Attr OBJECT = new Attr( "object" );
    public static final Attr ONBLUR = new Attr( "onblur" );
    public static final Attr ONCHANGE = new Attr( "onchange" );
    public static final Attr ONCLICK = new Attr( "onclick" );
    public static final Attr ONDBLCLICK = new Attr( "ondblclick" );
    public static final Attr ONFOCUS = new Attr( "onfocus" );
    public static final Attr ONKEYDOWN = new Attr( "onkeydown" );
    public static final Attr ONKEYPRESS = new Attr( "onkeypress" );
    public static final Attr ONKEYUP = new Attr( "onekeyup" );
    public static final Attr ONLOAD = new Attr( "onload" );
    public static final Attr ONMOUSEDOWN = new Attr( "onmousedown" );
    public static final Attr ONMOUSEMOVE = new Attr( "onmousemove" );
    public static final Attr ONMOUSEOUT = new Attr( "onmouseout" );
    public static final Attr ONMOUSEOVER = new Attr( "onmouseover" );
    public static final Attr ONMOUSEUP = new Attr( "onmouseup" );
    public static final Attr ONRESET = new Attr( "onreset" );
    public static final Attr ONSELECT = new Attr( "onselect" );
    public static final Attr ONSUBMIT = new Attr( "onsubmit" );
    public static final Attr ONUNLOAD = new Attr( "onunload" );
    public static final Attr PROFILE = new Attr( "profile" );
    public static final Attr PROMPT = new Attr( "prompt" );
    public static final Attr READONLY = new Attr( "readonly" );
    public static final Attr REL = new Attr( "rel" );
    public static final Attr REV = new Attr( "rev" );
    public static final Attr ROWS = new Attr( "rows" );
    public static final Attr ROWSPAN = new Attr( "rowspan" );
    public static final Attr RULES = new Attr( "rules" );
    public static final Attr SCHEME = new Attr( "scheme" );
    public static final Attr SCOPE = new Attr( "scope" );
    public static final Attr SCROLLING = new Attr( "scrolling" );
    public static final Attr SELECTED = new Attr( "selected" );
    public static final Attr SHAPE = new Attr( "shape" );
    public static final Attr SIZE = new Attr( "size" );
    public static final Attr SPAN = new Attr( "span" );
    public static final Attr SRC = new Attr( "src" );
    public static final Attr STANDBY = new Attr( "standby" );
    public static final Attr START = new Attr( "start" );
    public static final Attr STYLE = new Attr( "style" );
    public static final Attr SUMMARY = new Attr( "summary" );
    public static final Attr TABINDEX = new Attr( "tabindex" );
    public static final Attr TARGET = new Attr( "target" );
    public static final Attr TEXT = new Attr( "text" );
    public static final Attr TITLE = new Attr( "title" );
    public static final Attr TYPE = new Attr( "type" );
    public static final Attr USEMAP = new Attr( "usemap" );
    public static final Attr VALIGN = new Attr( "valign" );
    public static final Attr VALUE = new Attr( "value" );
    public static final Attr VALUETYPE = new Attr( "valuetype" );
    public static final Attr VERSION = new Attr( "version" );
    public static final Attr VLINK = new Attr( "vlink" );
    public static final Attr VSPACE = new Attr( "vspace" );
    public static final Attr WIDTH = new Attr( "width" );

    private static final class Attr extends XUIWriterAttributeConst {
            public Attr( String sAttrName ) {
                super( sAttrName );
            }
    }

}
