package netgest.bo.xwc.xeo.beans;

public enum XEOEditBeanEventType {
	BEFORE_CREATE,
	AFTER_CREATE,
	BEFORE_VALIDATE,
	AFTER_VALIDADE,
	BEFORE_SAVE,
	AFTER_SAVE,
	BEFORE_CLOSE,
	AFTER_CLOSE,
	BEFORE_REMOVE,
	AFTER_REMOVE
}
